[RFC] add sitevision-scripts
strt/restapp-boilerplate pull request #4
Opened 2018-12-17 09:13 UTC by alexandernanberg

Refactor to use https://github.com/strt/sitevision/tree/master/packages/sitevision-scripts instead of SiteVisions utils.

This is still very WIP but I wanted to get some opinions on this before I continue.

Main changes
- `sitevision-scripts` will provide all the utils/scripts we need to handle addons. 
- `manifest.json` is generated from the `package.json` file (a lot of properties were already duplicated, only hade to add `type` + `displayName`).
- `.dev-properties.json` is removed in favor of a `.env` file.

Also have some ideas of a `dev` command that will watch the `src` files for changes and build + deploy them directly.

Let me know what you think 😄

2018-12-17 13:04 UTC, jesperjohansson requested changes
Provide information in the readme.

2018-12-17 13:07 UTC, alexandernanberg commented
@jesperjohansson I think if this get accepted that we should move away from this fork and create new repo. A readme would be created/updated then instead

2018-12-19 15:36 UTC, alexpkarlsson requested changes
Some minor changes. Also update `yarn.lock` to new `sitevision-scripts` version.

2018-12-19 15:36 UTC, alexkstrt commented on package.json
> +    "sitevision-scripts": "^0.1.0"
```suggestion
    "sitevision-scripts": "^0.3.0"
```

Bump to most recent version.

2018-12-19 15:36 UTC, alexkstrt commented on package.json
>    "name": "restapp-boilerplate",
Add `displayName` as well to signal that it should exist.

2018-12-19 15:36 UTC, alexkstrt commented on package.json
> +    "prod-deploy": "echo 'todo'"
```suggestion
    "prod-deploy": "sitevision-scripts deploy --production"
```

Implement new `--production` flag added in `0.3.0`.

2018-12-20 08:54 UTC, alexkstrt commented on package.json
> +    "prod-deploy": "echo 'todo'"
Actually, might be better to just remove this and force the use to simply run `deploy --production`?

2018-12-20 09:34 UTC, alexpkarlsson approved these changes

2019-02-25 10:01 UTC, jesperjohansson approved these changes

2019-02-25 10:02 UTC, merged